### ISSUE TITLE
MIT License Violation

### ISSUE THREAD

**Issue by techchrism** [tratteo/LiterallyChunkLoader-1.16#1]
I noticed you copied and pasted my mod's code which is okay as long as it complies with my mod's license.
In this case, it does not.
Please see https://github.com/techchrism/TickTock/blob/trunk/LICENSE
> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

**Comment by tratteo** [comment]
Here you go: https://github.com/tratteo/LiterallyChunkLoader-1.16/blob/master/src/main/java/net/literally/chunk/loader/initializer/LCLTicker.java
